// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantSwap.Models;

namespace PlantSwap.Migrations
{
    [DbContext(typeof(PlantSwapContext))]
    [Migration("20220310174434_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PlantSwap.Models.Swap", b =>
                {
                    b.Property<int>("SwapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CuisineType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("IngredientToSwap")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapOne")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapOneAbout")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapOneFlavorNotes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapOnePrep")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapThree")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapThreeAbout")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapThreeFlavorNotes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapThreePrep")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapTwo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapTwoAbout")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapTwoFlavorNotes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SwapTwoPrep")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SwapId");

                    b.ToTable("Swaps");
                });
#pragma warning restore 612, 618
        }
    }
}
